FROM python:3.11-slim

# Update system packages to fix vulnerabilities
RUN apt-get update && apt-get upgrade -y && apt-get clean

# Set the working directory
WORKDIR /app

# Copy the application files
COPY . /app

# Install dependencies
RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

# Expose the application port (Flask typically runs on 5000)
EXPOSE 5000

# Set the entry point to run the Flask app
CMD ["python", "app.py"]
